topics:
  -
    topic: /odom
    type: nav_msgs/msg/Odometry
    queue_size: 1
  -
    topic: /cmd_vel_mux/input/navi
    type: geometry_msgs/msg/Twist
    queue_size: 1
  -
    topic: /tf
    type: tf2_msgs/msg/TFMessage
    queue_size: 1
  -
    topic: /tf_static
    type: tf2_msgs/msg/TFMessage
    queue_size: 1
    qos:
      history: keep_all
      durability: transient_local
  -
    topic: /scan
    type: sensor_msgs/msg/LaserScan
    queue_size: 1   
      
# services_1_to_2:

# services_2_to_1:
